source.. = src/main/java/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               bin/,\
               plugin.xml,\
               build.properties,\
               application.yml,\
               knowledge/,\
               requirement-rules.yml,\
               architecture-rules.yml,\
               module-rules.yml,\
               aadl-rules.yml,\
               aadl-fixer-rules.yml,\
               lib/